### ISSUE TITLE
stuck by hydra when running on slurm cluster

### ISSUE THREAD

**Issue by bibisbar** [Flash-321/ARLDM#7]
Hi, when I tried to run this program on our slurm cluster, I can only get the seed output `Global seed set to 1` and nothing else. After checking, I think the problem may be the hydra decorator. Seems like the main function did not even be executed. Do you have some experience or recommendations regarding this problem? It would be really helpful and thanks in advance:)

**Comment by xichenpan** [comment]
Hi @bibisbar, thansk for you attention! This is a good question, and thanks for open an issue to point it out. I guess it is a hydra issue. I have used pytorch lightning in slurm cluster and it worked fine. To disable hydra, you need to change https://github.com/Flash-321/ARLDM/blob/81523af705a1895e4aa827dc7482501b4be664c8/main.py#L453-L454
into
```python
def main():
```
as for the config, you may now setup a argparser or maybe use 
```python
from omegaconf import OmegaConf
args= OmegaConf.load('config.yaml')
```
to load yaml config, so that you do not need to modify the code.
